---

- hosts: all
  become: true
  tasks:
    - name: Install httpd
      ansible.builtin.dnf:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat" and ansible_distribution_major_version | int > 8
    - name: Install apache2
      ansible.builtin.apt:
        name: apache2
        state: present
      when: ansible_distribution == "Debian"