---

- hosts: all
  become: true
  vars:
    users:
       - {name: karel, uid: 1234, shell: /bin/bash, comment: nejvetsi borec}
       - {name: pepa, uid: 2345, shell: /sbin/nologin, comment: porad zapomina}
       - {name: honza, uid: 3456, shell: /bin/sh, comment: nic neumi}
       - {name: jarek, uid: 4567, shell: /bin/true, comment: nechodi do prace}
       - {name: jakub, uid: 5678, shell: /bin/false, comment: na vyhozeni}
  tasks:
    - name: Create a users
      ansible.builtin.user:
        name: "{{item.name}}"
        uid: "{{item.uid}}"
        shell: "{{item.shell}}"
        comment: "{{item.comment}}"
      with_items: "{{users}}"