---

- hosts: all
  become: true
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /home/student/ansible/files/sudoers
        dest: /etc/sudoers
        owner: root
        group: root
        mode: u=r,g=r